// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TestRepo.Repository;

#nullable disable

namespace TestRepo.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260328141907_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TestRepo.Repository.Enity.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("229f722d-0d1f-4a37-8c73-5b20f0ef055e"),
                            IsDeleted = false,
                            Name = "Áo"
                        },
                        new
                        {
                            Id = new Guid("530147c4-93af-4594-b901-10e4687b7f86"),
                            IsDeleted = false,
                            Name = "Qần"
                        },
                        new
                        {
                            Id = new Guid("cb27c07b-f4bb-4b83-8330-cdcf003f9af0"),
                            IsDeleted = false,
                            Name = "Áo 3 lo",
                            ParentId = new Guid("229f722d-0d1f-4a37-8c73-5b20f0ef055e")
                        },
                        new
                        {
                            Id = new Guid("2fd95ed2-7574-4393-8529-afc62aa4c279"),
                            IsDeleted = false,
                            Name = "Quần 3 lo",
                            ParentId = new Guid("530147c4-93af-4594-b901-10e4687b7f86")
                        });
                });

            modelBuilder.Entity("TestRepo.Repository.Enity.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SellerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b5c2a90-c630-46be-822e-7188b58c6ad4"),
                            IsDeleted = false,
                            Name = "Product1",
                            Price = 12435m,
                            SellerId = new Guid("c894ac13-8ed2-4c78-8456-cda96fb7ee3a")
                        });
                });

            modelBuilder.Entity("TestRepo.Repository.Enity.Seller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c894ac13-8ed2-4c78-8456-cda96fb7ee3a"),
                            CompanyAddress = "CompanyAddress",
                            CompanyName = "CompanyName",
                            IsDeleted = false,
                            TaxCode = "taxcode",
                            UserId = new Guid("fc120386-aa74-44b2-b524-3c54f73b3b71")
                        });
                });

            modelBuilder.Entity("TestRepo.Repository.Enity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fc120386-aa74-44b2-b524-3c54f73b3b71"),
                            Email = "Anhpham@gmai.com",
                            IsDeleted = false,
                            Password = "password"
                        },
                        new
                        {
                            Id = new Guid("15dc622f-7997-4b00-aa81-5c077b22f7ef"),
                            Email = "Anhpham123@gmai.com",
                            IsDeleted = false,
                            Password = "password"
                        });
                });

            modelBuilder.Entity("TestRepo.Repository.Enity.Category", b =>
                {
                    b.HasOne("TestRepo.Repository.Enity.Category", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TestRepo.Repository.Enity.Product", b =>
                {
                    b.HasOne("TestRepo.Repository.Enity.Seller", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("TestRepo.Repository.Enity.Seller", b =>
                {
                    b.HasOne("TestRepo.Repository.Enity.User", "User")
                        .WithOne("Seller")
                        .HasForeignKey("TestRepo.Repository.Enity.Seller", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TestRepo.Repository.Enity.Seller", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TestRepo.Repository.Enity.User", b =>
                {
                    b.Navigation("Seller")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
